services:
  db:
    image: postgres:15
    container_name: nulltrace-db
    restart: always
    environment:
      POSTGRES_DB: nulltrace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./flask_backend/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5433:5432"

  backend:
    container_name: nulltrace-backend
    build: ./flask_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: nulltrace
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "5000:5000"

  frontend:
    container_name: nulltrace-frontend
    build: ./frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:5000
    ports:
      - "3000:3000"

volumes:
  postgres_data: